# Generated by Django 4.1 on 2022-09-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('secondSurname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('heartRate', models.IntegerField(help_text='Frecuencia Cardiaca(Heart Rate) medida en BPM(Beats per minute)/Pulsaciones por minuto')),
                ('bloodOxygenSaturation', models.IntegerField(help_text='Saturación de Oxígeno en Sangre')),
                ('stresslevel', models.CharField(choices=[('l', 'Low'), ('m', 'Moderate'), ('h', 'High'), ('e', 'Extreme')], default='l', help_text='Nivel de estrés', max_length=1)),
            ],
            options={
                'db_table': 'metrics',
            },
        ),
    ]
