# Generated by Django 4.1 on 2022-09-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrics',
            old_name='secondSurname',
            new_name='surnames',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='surname',
        ),
    ]
