# Generated by Django 4.1 on 2022-09-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0003_alter_metrics_stresslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
